### ISSUE TITLE
Embedded Components

### ISSUE THREAD

**Issue by klongmitre** [arun-prakash-fokus/vue-goldenlayout-dynamic#1]
Hi - great example and it works great with flat components, but it seems that if the component includes a component inside of it, that it doesn't get loaded correctly. Have you tried this approach using components that include other components?

**Comment by arun-prakash-fokus** [comment]
Hi, 
yes, I have tried it and it works out. I have updated the example. 
`Component1` now is composed of its own content and a new Vue component called `NestedComponent`
Do check out and let me know if this what you mean.

**Comment by klongmitre** [comment]
@arun-prakash-fokus - Sorry about the delayed response. It appears the issue I was having was not related to the nesting of components. Thanks for the example!
